/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpinningRouteImport } from './routes/spinning'
import { Route as SnippetRouteImport } from './routes/snippet'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as FormRouteImport } from './routes/form'
import { Route as IndexRouteImport } from './routes/index'

const SpinningRoute = SpinningRouteImport.update({
  id: '/spinning',
  path: '/spinning',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetRoute = SnippetRouteImport.update({
  id: '/snippet',
  path: '/snippet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/reading': typeof ReadingRoute
  '/snippet': typeof SnippetRoute
  '/spinning': typeof SpinningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/reading': typeof ReadingRoute
  '/snippet': typeof SnippetRoute
  '/spinning': typeof SpinningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/reading': typeof ReadingRoute
  '/snippet': typeof SnippetRoute
  '/spinning': typeof SpinningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/reading' | '/snippet' | '/spinning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/reading' | '/snippet' | '/spinning'
  id: '__root__' | '/' | '/form' | '/reading' | '/snippet' | '/spinning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRoute: typeof FormRoute
  ReadingRoute: typeof ReadingRoute
  SnippetRoute: typeof SnippetRoute
  SpinningRoute: typeof SpinningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spinning': {
      id: '/spinning'
      path: '/spinning'
      fullPath: '/spinning'
      preLoaderRoute: typeof SpinningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippet': {
      id: '/snippet'
      path: '/snippet'
      fullPath: '/snippet'
      preLoaderRoute: typeof SnippetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRoute: FormRoute,
  ReadingRoute: ReadingRoute,
  SnippetRoute: SnippetRoute,
  SpinningRoute: SpinningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
